const COLLECTIONS = {
  "associated-press": "the Associated Press",
  "baller-ape-club": "the people behind Baller Ape Club",
  bayc: "Bored Ape Yacht Club",
  binance: "Binance",
  "canada-convoy": "the Canada convoy protest",
  "celebrity-rugpull": "celebrity rug pulls",
  "class-action": "class action lawsuits",
  coinbase: "Coinbase",
  cream: "C.R.E.A.M. Finance",
  "crypto-com": "Crypto.com",
  cryptopunks: "CryptoPunks",
  "doodled-dragons": "the people behind Doodled Dragons",
  "gary-vee": "Gary Vaynerchuk",
  "jacked-apes": "Jacked Ape Club",
  kickstarter: "Kickstarter",
  looksrare: "LooksRare",
  "melania-trump": "Melania Trump",
  metamask: "MetaMask",
  opensea: "OpenSea",
  qubit: "Qubit Finance",
  tether: "Tether",
  twitter: "Twitter",
  ubisoft: "Ubisoft",
  "value-defi": "Value DeFi",
  voiceverse: "VoiceVerse",
  wonderland: "Wonderland",
};

export default COLLECTIONS;
